on: [ push, pull_request ]
name: Build

jobs:
  build:
    name: "Build and test"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest,  macos-latest, windows-latest]
        rust: [stable]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install ${{ matrix.rust }} toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - name: cargo build
        run: cargo build
